# -*- coding: utf-8 -*-
"""image recognision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r__tpkSSMcehpj6ctVxYtGQAp5Dmdytp
"""

from google.colab import drive
drive.mount('/content/gdrive')

!pip install dlib
!pip install face_recognition

import os
import face_recognition

#os.chdir method changes the current working directory to the given path
os.chdir('/content/gdrive/My Drive/Trial')

#os.listdir is used to get the list of all files and directories in the specified directory
#It therefore makes the images available for training. 
images = os.listdir('/content/gdrive/My Drive/Trial')

# uploading the image we want to check whether it exits in out "corpus"
checked_image = face_recognition.load_image_file('/content/gdrive/My Drive/Getting/corpus/inno1.jpg')

# encoding the uploaded image. Why?
checked_image_encoded = face_recognition.face_encodings(
    checked_image)[0]

# iterating over every image in corpus to check for uploaded image
for image in images:
    current_image = face_recognition.load_image_file("/content/gdrive/My Drive/Trial/" + image)
    current_image_encoded = face_recognition.face_encodings(current_image)[0]
    result = face_recognition.compare_faces(
        [checked_image_encoded], current_image_encoded)
  
    if result[0] == True:
        print("Corpus, uploaded image is: " + image)
    else:
      print("Visitor, uploaded image is not: " + image)



